defaults:
  - model: lcnn
  - datasets: asvspoof_eval
  - dataloader: asvspoof
  - transforms: asvspoof
  - _self_

submission:
  checkpoint: /kaggle/working/final_run/model_best.pth
  output_path: /kaggle/working/final_run/submission.csv
  device: auto
  seed: 1
